# Generated by Django 4.2.17 on 2025-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionattempt',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
