# Generated by Django 4.2.15 on 2024-11-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ratings',
            field=models.ManyToManyField(related_name='course_ratings', to='courses.rating'),
        ),
    ]
