# Generated by Django 4.2.16 on 2024-11-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='social_media',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='fb',
            field=models.CharField(default='www.facebook.com/', max_length=255),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='linkedin',
            field=models.CharField(default='www.linkedin.com/', max_length=255),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='tiktok',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='twitter',
            field=models.CharField(default='www.x.com/', max_length=255),
        ),
    ]
