# Generated by Django 4.2.16 on 2024-11-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_full_name_staffmember_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
