# Generated by Django 4.2.16 on 2024-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_staffmember_telegram_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
