# Generated by Django 4.2.15 on 2024-12-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='fb',
            field=models.CharField(default='https://www.facebook.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='linkedin',
            field=models.CharField(default='https://www.linkedin.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='twitter',
            field=models.CharField(default='https://www.x.com/', max_length=255),
        ),
    ]
