# Generated by Django 4.2.17 on 2024-12-23 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_staffmember_fb_alter_staffmember_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.FileField(upload_to='course/lessons/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'mkv', 'flv', 'mpeg', 'doc', 'docx', 'pdf', 'txt', 'rtf', 'odt', 'html', 'htm'])]),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
