# Generated by Django 4.2.17 on 2024-12-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_preview_alter_studentscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
